PUT http://localhost:8080/events/1
Content-Type: application/json

{
  "name": "Christmas Party 2",
    "description": "Join us for a festive celebration with more fun!",
    "location": "219 Celebration Ave",
    "dateTime": "2024-02-10T10:00:00Z",
    "userId": 13

}