DELETE http://localhost:8080/events/11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUzNDU3NTIxLCJ1c2VySWQiOjF9.cSDvfEmsLt3cPLcDJyEutDOem6GBhn2ITCnJOUD1Y3k