DELETE http://localhost:8080/events/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUzNDUxNDcyLCJ1c2VySWQiOjF9.byTyu1Vm_3G1ZpX6ttI9MJ6_I6NLYe-fHQaZ1eOJexc