POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUzNDU5MTU1LCJ1c2VySWQiOjJ9.g8hV3xi0U25__t2P0H6ic2HE9csKLW1pNj5AeAtNP-8